### ISSUE TITLE
Plot markers in map. 

### ISSUE THREAD

**Issue by CesMak** [gareth-cross/rviz_satellite#34]
Hey there,
I just want to plot gps points with markers on a map. Therefore I want to use your rviz_satellite package.
To do that I launched your demo file and also played the sample.bag file. Next I tried to create a marker that subscribes to topic /gps/fix. This however did not work for me ..... 

question: 
How to use the bagfile correctely and display gps data as markers?

Hope you can help me.

Best
Markus

**Comment by beetleskin** [comment]
very unrelated to this plugin, @schra plz close.

**Comment by schra** [comment]
@CesMak We won't add such a functionality to this plugin since this plugin is solely for displaying a map.
