### ISSUE TITLE
How to replace openstreetmap with Google Map

### ISSUE THREAD

**Issue by nofear123** [gareth-cross/rviz_satellite#46]
Compared with Google,OpenStreetMap and MapBox are updated slowly.So I found the URI of Google tiles Maps on the Internet. Then I directly replaced the object uri with the uri of Google Maps on AerialMapDisplay.
In the end, although Google Maps can be displayed on the rviz, the scale of the map is incorrect, **so some people know how to modify the scale**?

Thank you.

**Comment by beetleskin** [comment]
what link-template and other settings are you using?

**Comment by nofear123** [comment]
This is my link to use the Google map, you can try it.This link has a lot of parameters to adjust.
http://mt2.google.cn/vt/lyrs=y&scale=1&hl=zh-CN&gl=cn&x={x}&y={y}&z={z}

**Comment by beetleskin** [comment]
it works for me with http://mt0.google.com/vt/lyrs=s&hl=en&x={x}&y={y}&z={z}&s=Ga

Maybe play a bit with the other params?
However, using those links without api is deprecated and might have some legal issues. Just fyi.

**Comment by nofear123** [comment]
Yes, your link is useful. I compared your link to my link  and modified some params. I found the parameter in my link that caused my problem is "&gl=cn". Thank you for your answer.

**Comment by nofear123** [comment]
> it works for me with [http://mt0.google.com/vt/lyrs=s&hl=en&x={x}&y={y}&z={z}&s=Ga](http://mt0.google.com/vt/lyrs=s&hl=en&x=%7Bx%7D&y=%7By%7D&z=%7Bz%7D&s=Ga)
> 
> Maybe play a bit with the other params?
> However, using those links without api is deprecated and might have some legal issues. Just fyi.

@beetleskin Thanks for your answer.

**Comment by atasoglou** [comment]
Is the google link still working to date? We are getting "Bad request" errors.
