### ISSUE TITLE
Tile Loader not showing the tiles in the proper place

### ISSUE THREAD

**Issue by david-alejo** [gareth-cross/rviz_satellite#48]
Dear all,

First of all, thank you for the development of this plugin that I've found very handy.

I upgraded to the latest version yesterday to make it work in 18.04. I have found that now the satellite images are no longer in the proper placed. Instead, they appear with a small shift to the South and East.

I attach an example with the representation of coordinates 41.38738993 N  2.183433017 E in google maps and with your plugin in rviz to help to understand the differences.

Has any other noticed it?
![issue_rviz_satellite](https://user-images.githubusercontent.com/14801710/54298350-de74b400-45b8-11e9-9607-776a4db49220.png)
![Screenshot from 2019-03-13 17-44-04](https://user-images.githubusercontent.com/14801710/54298352-de74b400-45b8-11e9-8ac8-3d391da52431.png)

**Comment by beetleskin** [comment]
Is your robot_frame equal to the frame_id in the NavSat message?

Could you provide a minimum working example to reproduce, via a PR?

**Comment by david-alejo** [comment]
Thank you for your kind response. I'm checking the frame_id and if I can't correct it, I will provide a MWE.

Regarding to the tile served, I checked Google Maps and OpenStreetMap.

**Comment by david-alejo** [comment]
I created a PR related to this issue as a minimum working example. In it, you can see a marker and the axes in the reference frame map. They do not correspond with the location of /gps/fix when using google maps.

**Comment by beetleskin** [comment]
Well, the demo is currently not working properly, the display produces an error. In your PR, please add

`<node pkg="tf2_ros" type="static_transform_publisher" name="static_transform_base_link_applanix" args="0 0 0 0 0 0 map base_link" />
` and set the robot_frame to base_link. And try again.

Can you confirm that this works? If so, this is a duplicate of #49.

**Comment by david-alejo** [comment]
Interesting. By doing so the tiles are loaded OK.

However, it is not clear why this is necessary. I mean: the plugin was configured to have /map as robot frame, why is it necessary to use the base_link frame?

**Comment by beetleskin** [comment]
Its not necessary (I think) - but some frames need to be defined. That's true for most Display plugins, and for RViz itself.

**Comment by david-alejo** [comment]
Ok it makes sense, I'm closing the issue as it is somehow duplicated with yours.

Thank you for your kind responses. Best regards,

**Comment by beetleskin** [comment]
@schra maybe this isn a pure duplicate - I think the plugin should complain if frames are missing, rather than rendering bullshit. What do you think?

**Comment by schra** [comment]
> @schra maybe this isn a pure duplicate - I think the plugin should complain if frames are missing, rather than rendering bullshit. What do you think?

Good point. I created an issue for this.
