### ISSUE TITLE
Wrong location in demo

### ISSUE THREAD

**Issue by Martin-Oehler** [gareth-cross/rviz_satellite#84]
I tried to run the demo and was shown the following location:
![rviz_screenshot_2020_06_15-15_10_06](https://user-images.githubusercontent.com/7110154/84661365-898dbf00-af1a-11ea-913f-d4b758eee120.png)
If I enter the same coordinates into a different site, I am shown a different location, which appears to be further in the south.

![image](https://user-images.githubusercontent.com/7110154/84661296-74b12b80-af1a-11ea-8955-46393f129a70.png)
https://www.latlong.net/c/?lat=39.951121&long=-75.189930
It looks like, rviz_satellite is misreporting the position. Am I missing something here?

Best regards,
Martin Oehler

**Comment by beetleskin** [comment]
Can confirm, looks like this was introduced in 5431732.

**Comment by Martin-Oehler** [comment]
I can confirm, that 0028d57dceca888cad3e27239e132d15dd713cf0 does not show this behavior.

**Comment by lyrem0007a** [comment]
I still have the same problem. 48.197119, 11.578062.

**Comment by mishrasubhransu** [comment]
Still have the same issue [[39.326465, -76.621554]. First image is incorrect and second image is correct location. 
![image](https://user-images.githubusercontent.com/598837/87607816-356a2c00-c6cc-11ea-8747-a7a3bfc8d006.png)
![image](https://user-images.githubusercontent.com/598837/87607840-3e5afd80-c6cc-11ea-8a61-7afeba537df2.png)

**Comment by lyrem0007a** [comment]
I check out 0028d57 and it works well.

**Comment by beetleskin** [comment]
Please check out #85, it's waiting for reviewand should fix this.

**Comment by schra** [comment]
Fix is merged now
