### ISSUE TITLE
Wrong tile positioning

### ISSUE THREAD

**Issue by blacksoul000** [gareth-cross/rviz_satellite#90]
Tile is always positioning with left bottom corner in (0, 0)

ROS version: 
foxy/noetic

Steps to reproduce:
Publish gps position with rqt and open plugin in rviz

RViz result:
![Screenshot_20201030_110755](https://user-images.githubusercontent.com/5609587/97675331-2f902f00-1aa0-11eb-806d-b8e335b24000.png)

OSM result:
![Screenshot_20201030_105251](https://user-images.githubusercontent.com/5609587/97675361-3b7bf100-1aa0-11eb-87ba-2593c1f63d74.png)

p.s. got this bug on foxy but reproduced at noetic
p.p.s. if i will increase latitude for example position in rviz not changing. Only loaded tile may be changed

**Comment by ceranit** [comment]
In what frame is your NavSatFix published? It should either be "map" or your should change the `AerialMapDisplay::MAP_FRAME` in line 62 of _aerialmap_display.cpp_ to whatever your frame_id is. I had a similar problem in eloquent/melodic so I hope this fix works for you too.

**Comment by blacksoul000** [comment]
@ceranit 
In 'map' frame. Have you tried the same?
**RViz**
Fixed frame: map
Object URI: https://tile.openstreetmap.org/{z}/{x}/{y}.png
zoom: 17
blocks: 0
**Rqt**
frame: map
latitude: 33.893962
longitude: -77.036484

**Comment by ceranit** [comment]
@blacksoul000 Yeah for me the problem was that the frames didn't match so changing it to "map" fixed it. But using those setting it looks fine to me

![Screenshot from 2020-11-12 11-29-28](https://user-images.githubusercontent.com/49021015/98928667-5b68d700-24da-11eb-8783-901db02bd284.png)
